### ISSUE TITLE
overriding defaults in component doesn't work

### ISSUE THREAD

**Issue by evdama** [EmilTholin/svelte-spinner#11]
I have created a default spinner component with `color='green'`:
```js
// Spinner.svelte

<script>
  import Spinner from 'svelte-spinner'
</script>

<style>
    :global(.svelte-spinner) {
        display: inline;
    }
</style>

<Spinner
  size="40"
  speed="600"
  color="green"
  thickness="1.5"
  gap="40">
</Spinner>
```

Then in my App.svelte I'd like to override the color using red

```js
// App.svelte
<script>
  import Spinner from '../Spinner.svelte'
</script>

    <Spinner
  color="red"
  thickness="2"
/>
```
but the color and all other properties remain what's set as the default above e.g. color remains green. What am I missing?

**Comment by EmilTholin** [comment]
You are not passing the props given to your own `Spinner` component to the `svelte-spinner` component.

**Comment by evdama** [comment]
Can you give an example please? I tried `let color = 'purple'` in inside the script tag but still, if I go on and use `<Spinner color='green'></Spinner> then it's still not green...
