### ISSUE TITLE
Rename index.html to index.svelte

### ISSUE THREAD

**Issue by PaulMaly** [EmilTholin/svelte-spinner#2]
Seems, if we want to use Svelte components in different environments we should use a custom extension to prevent any conflicts with existing webpack/rollup configs.

**Comment by EmilTholin** [comment]
Hi @PaulMaly!

Yeah, it's a bit of a hassle. If we change to `.svelte` it will stop working for others which have a working configuration for `.html`.

I'm subscribing to the [Convention for packaged components to export uncompiled templates](https://github.com/sveltejs/svelte/issues/604) issue and will implement that when something generic is implemented.

**Comment by PaulMaly** [comment]
> Yeah, it's a bit of a hassle. If we change to .svelte it will stop working for others which have a working configuration for .html.

I think it's very simple to fix that )))

```
test: /\.(html|svelte)$/,
```

**Comment by EmilTholin** [comment]
I changed to the `.svelte` file extension in `2.0.0`.
