### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [EmilTholin/svelte-spinner#3]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by EmilTholin** [comment]
Hi @mansya!

That is very kind of you! Keep in mind that this is not a very popular project, so your talent and time might be better spent on a larger project, but if you feel like creating a logo that would be great.

**Comment by mansya** [comment]
it doesn't matter if this isn't a big project. I just want to design a logo for this project so that this project looks perfect and becomes a big project someday. I will design it. you can wait for it.

**Comment by mansya** [comment]
hi sir. sorry for my delay in responding to this conversation. I have designed a logo for this simple project. do you like it ? if yes. which one do you like?
![svelte spinner](https://user-images.githubusercontent.com/33461607/45585331-ddfea780-b90c-11e8-91cc-121a7f521ecf.png)

**Comment by EmilTholin** [comment]
Hey @mansya! It looks really good! I like them all. Is there anyone of them you like the most? Maybe it could also be cool with `#A82124` as background color, which is the color of the spinner in the README example?

**Comment by mansya** [comment]
I have uploaded all files to this [**Drive**](https://drive.google.com/open?id=1CHzvC9ccHFrjWAi89BDYefDoAzg2SyGO). and I have also sent you [**Pull Requests.**](https://github.com/EmilTholin/svelte-spinner/pull/4) please check.

**Comment by EmilTholin** [comment]
It looks awesome! Thank you so much @mansya!

This issue is closed by https://github.com/EmilTholin/svelte-spinner/pull/4.
