### ISSUE TITLE
How to develop, locally?

### ISSUE THREAD

**Issue by akauppi** [EmilTholin/svelte-spinner#7]
The example currently depends on the published `svelte-spinner` artefact. 

How would you do local development, that is shorten the change code - run example cycle?

**Comment by akauppi** [comment]
I forked the repo to try push local dev-and-demo loop speed, see [here](https://github.com/akauppi/svelte-spinner). My aim is simply to get a good template for creating a component I need. Chose svelte-spinner as the basis, since it seems the best currently available.

**Comment by EmilTholin** [comment]
Hi @akauppi!

The repository example now works with the latest node versions after https://github.com/EmilTholin/svelte-spinner/pull/6 was merged.
